services:
   db:
      image: mongo
      container_name: maw-db
      ports:
         - '27017:27017'
      volumes:
         - mongo-data:/data/db

   server:
      build: server
      container_name: maw-server
      ports:
         - '5000:5000'
      environment:
         MONGODB_URI: mongodb://localhost:27017/mawdb
      depends_on:
         - db

   client:
      build: client
      container_name: maw-client
      ports:
         - '3000:3000'
      depends_on:
         - server

volumes:
   mongo-data:
