services:
   client:
      build:
         context: ./client
      container_name: maw-client
      ports:
         - '3000:3000'
      develop:
         watch:
            - path: ./client/package.json
              action: rebuild
            - path: ./client
              target: /app
              action: sync

   server:
      build:
         context: ./server
      container_name: maw-server
      ports:
         - '5000:5000'
      environment:
         PORT: 5000
         MONGODB_URI: mongodb://maw-db:27017/mawdb
         JWT_ACCESS_SECRET: Ad9AeTd+sXLmCyxZKW1a6etcHXzRNpIqDOrv/C73KHwsh4AN+5bT
         JWT_REFRESH_SECRET: RN/SyhIA3oIwPVmuiH0AZECddaKYCTlrYoAeiyVZ5sIwoFKp1L6l
      depends_on:
         - db
      develop:
         watch:
            - path: ./server
              action: rebuild

   db:
      image: mongo
      container_name: maw-db
      ports:
         - '27017:27017'
      volumes:
         - maw-data:/data/db

volumes:
   maw-data:
